import type { MetricDefinition } from "./types";

export const metricDefinitions: MetricDefinition[] = [
  {
    id: "lighthouse_score",
    name: "新灯塔分",
    domainId: "service",
    sourceIds: ["new_lighthouse", "manual_input"],
    unit: "score",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "1688 新灯塔页面展示的店铺服务体验综合分。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "consultation_experience_score",
    name: "咨询体验分",
    domainId: "service",
    sourceIds: ["new_lighthouse", "manual_input"],
    unit: "score",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "新灯塔中咨询体验维度分。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "ww_3min_response_rate",
    name: "旺旺 3 分钟响应率",
    domainId: "service",
    sourceIds: ["new_lighthouse", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "旺旺有效咨询在 3 分钟内响应的比例。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "refund_processing_duration",
    name: "退款处理时长",
    domainId: "service",
    sourceIds: ["new_lighthouse", "after_sales_backend", "manual_input"],
    unit: "hour",
    direction: "lower_is_better",
    cadence: "30d",
    definition: "近 30 天退款处理平均时长。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "intervention_rate",
    name: "平台介入率",
    domainId: "guardrail",
    sourceIds: ["new_lighthouse", "after_sales_backend", "manual_input"],
    unit: "%",
    direction: "lower_is_better",
    cadence: "30d",
    definition: "售后或交易纠纷进入平台介入的比例。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "blocking"
  },
  {
    id: "procurement_index_score",
    name: "采购指数",
    domainId: "product_growth",
    sourceIds: ["product_growth_backend", "manual_input"],
    unit: "score",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "1688 商品成长体系中用于判断潜力商品和采购指数 4.0 商品的综合分。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "town_shop_treasure_count",
    name: "镇店之宝商品数",
    domainId: "product_growth",
    sourceIds: ["product_growth_backend", "manual_input"],
    unit: "count",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "当前可配置或已配置为镇店之宝的商品数量。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "quality_issue_product_count",
    name: "待优化商品数",
    domainId: "product_growth",
    sourceIds: ["product_growth_backend", "product_list", "manual_input"],
    unit: "count",
    direction: "lower_is_better",
    cadence: "daily",
    definition: "商品成长或商品列表中提示需要优化发布质量、属性、服务或表达的商品数量。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "total_exposure",
    name: "总曝光",
    domainId: "trade_funnel",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "count",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "店铺或商品获得的总展现次数。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "visitors",
    name: "访客",
    domainId: "trade_funnel",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "count",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "进入店铺或商品详情的访客数。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "inquiries",
    name: "询盘",
    domainId: "trade_funnel",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "count",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "旺旺、找工厂等有效咨询数。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "payments",
    name: "支付订单数",
    domainId: "trade_funnel",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "count",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "完成支付的订单数。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "payment_amount",
    name: "支付金额",
    domainId: "trade_funnel",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "money",
    direction: "higher_is_better",
    cadence: "daily",
    definition: "完成支付的成交金额。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "factory_service_response_rate",
    name: "找工厂服务响应率",
    domainId: "factory_custom",
    sourceIds: ["factory_workbench", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "找工厂有效服务咨询的响应比例。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "factory_fulfillment_rate",
    name: "找工厂履约率",
    domainId: "factory_custom",
    sourceIds: ["factory_workbench", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "找工厂或定制交易的履约完成比例。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "blocking"
  },
  {
    id: "custom_trade_points",
    name: "定制交易积分",
    domainId: "factory_custom",
    sourceIds: ["factory_workbench", "manual_input"],
    unit: "points",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "找工厂/定制相关交易对牌级成长贡献的积分。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "contract_payment_rate",
    name: "合约支付率",
    domainId: "factory_custom",
    sourceIds: ["factory_workbench", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "定制或找工厂合约订单完成支付的比例。",
    isOfficialMetric: true,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "repeat_buyer_rate",
    name: "老客复购率",
    domainId: "customer_repeat",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "近 30 天有复购行为的买家占比。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "watch"
  },
  {
    id: "repeat_payment_amount",
    name: "老客支付金额",
    domainId: "customer_repeat",
    sourceIds: ["sycm_core_board", "manual_input"],
    unit: "money",
    direction: "higher_is_better",
    cadence: "30d",
    definition: "近 30 天来自老客或复购客户的支付金额。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "none"
  },
  {
    id: "gross_margin_rate",
    name: "毛利率",
    domainId: "guardrail",
    sourceIds: ["internal_profit_sheet", "manual_input"],
    unit: "%",
    direction: "higher_is_better",
    cadence: "weekly",
    definition: "扣除主要成本后的真实毛利率。",
    isOfficialMetric: false,
    canBeGoalMetric: true,
    canBeVerificationMetric: true,
    guardrailLevel: "blocking"
  }
];
